torch.Size([10, 4, 2000])
INFO: Using device cuda
ERROR: Error importing optional module plotly.tools
Traceback (most recent call last):
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/util.py", line 121, in get_module
    return import_module(name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plotly'
[34m[1mwandb[0m: [32m[41mERROR[0m plotly is required to log interactive plots, install with: pip install plotly or convert the plot to an image with `wandb.Image(plt)`
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    train(net=net, device=device, batch_size=wandb.config.batch_size, lr=wandb.config.lr, epochs=wandb.config.epochs)
  File "train.py", line 48, in train
    wandb.log({"chart": plot})
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/__init__.py", line 746, in log
    run.log(row, commit, step, sync, *args, **kwargs)
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/wandb_run.py", line 651, in log
    self.history.add(row, *args, step=step, commit=commit, **kwargs)
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/history.py", line 139, in add
    self._write()
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/history.py", line 242, in _write
    self._transform()
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/history.py", line 225, in _transform
    self.row = data_types.history_dict_to_json(self._run, self.row)
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/data_types.py", line 1618, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, step=step)
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/data_types.py", line 1648, in val_to_json
    val = Plotly.make_plot_media(val)
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/data_types.py", line 1202, in make_plot_media
    "plotly.tools", required="plotly is required to log interactive plots, install with: pip install plotly or convert the plot to an image with `wandb.Image(plt)`")
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/util.py", line 128, in get_module
    raise wandb.Error(required)
wandb.core.Error: plotly is required to log interactive plots, install with: pip install plotly or convert the plot to an image with `wandb.Image(plt)`
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/history.py", line 242, in _write
    self._transform()
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/history.py", line 225, in _transform
    self.row = data_types.history_dict_to_json(self._run, self.row)
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/data_types.py", line 1618, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, step=step)
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/data_types.py", line 1648, in val_to_json
    val = Plotly.make_plot_media(val)
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/data_types.py", line 1196, in make_plot_media
    val = util.ensure_matplotlib_figure(val)
  File "/home/Wr1t3R/.local/share/virtualenvs/unet-YAYnS212/lib/python3.6/site-packages/wandb/util.py", line 290, in ensure_matplotlib_figure
    "You attempted to log an empty plot, pass a figure directly or ensure the global plot isn't closed.")
ValueError: You attempted to log an empty plot, pass a figure directly or ensure the global plot isn't closed.
